#!/bin/bash
echo -e "\e[31m Hello World"
echo -e "\e[32m Hello World"
echo -e "\e[33m Hello World"
echo -e "\e[34m Hello World"        
echo -e "\e[35m Hello World"
echo -e "\e[36m Hello World"
echo -e "\e[37m Hello World"    
echo -e "\e[1m Hello World"
echo -e "\e[4m Hello World"
echo -e "\e[0m Hello World \e[0m"
